# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GithubUsersList' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'SwiftyJSON'
  pod 'Alamofire'
  pod 'MBProgressHUD'

  # Pods for GithubUsersList

  target 'GithubUsersListTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GithubUsersListUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
